#!bash

. <("$ZENLOG_BIN" -s)

preexec() {
  "$ZENLOG_BIN" start-command-with-env "$(bash_dump_env)" $(bash_last_command)
}

prompt_command() {
  status=$?
  lines=$("$ZENLOG_BIN" stop-log -n $status)
  echo "Lines: $lines"
}

PS1='\$ '
PS0='$(preexec)'
PROMPT_COMMAND="prompt_command"

tick() {
  local num=${1:-1}
  echo $(( $(cat "$_ZENLOG_TIME_INJECTION_FILE") + $num )) > "$_ZENLOG_TIME_INJECTION_FILE"
}

stty -echo

# Override it.
ZENLOG_PID=$_ZENLOG_LOGGER_PID
