#!bash

last_command() {
  HISTTIMEFORMAT= history 1 | sed -e "s/^[ ]*[0-9]*[ ]*//"
}

preexec() {
  zenlog4 start-command $(last_command)
}

prompt_command() {
  zenlog4 stop-log
}

PS1='[\w \$\$=$$ ZENLOG4_PID=$ZENLOG4_PID]\n\$ '
PS0='$(preexec)'
PROMPT_COMMAND="prompt_command"
