#!bash

ZENLOG=$(readlink -m "$(dirname "${BASH_SOURCE[0]}")"/../zenlog)
echo $ZENLOG

. <("$ZENLOG" -s)

preexec() {
  "$ZENLOG" start-command $(bash_last_command)
}

prompt_command() {
  "$ZENLOG" stop-log
}

PS1='[\w \$\$=$$ ZENLOG_PID=$ZENLOG_PID]\n\$ '
PS0='$(preexec)'
PROMPT_COMMAND="prompt_command"
