#!/bin/bash

medir="${0%/*}"

export ZENLOG_RC="$medir/zenlogrc.rb"
export ZENLOG_START_COMMAND="/bin/bash --noprofile --rcfile $medir/bashrc"
export ZENLOG_DIR=~/zenlog-test
#export ZENLOG_DEBUG=1

export PATH="$medir/..:$PATH"
zenlog
