#!/bin/bash

medir="${0%/*}"

export ZENLOG4_RC="$medir/zenlogrc.rb"
export ZENLOG4_START_COMMAND="/bin/bash --noprofile --rcfile $medir/bashrc"
export ZENLOG4_DIR=~/zenlog4

export PATH="$medir/..:$PATH"
zenlog4
