#!/bin/bash

medir="${0%/*}"

export ZENLOG_BIN="$medir/../zenlog"
export ZENLOG_RC="$medir/zenlogrc.rb"
export ZENLOG_START_COMMAND="/bin/bash --noprofile --rcfile $medir/bashrc"
export ZENLOG_DIR=/tmp/zenlog-test
export ZENLOG_TIME_INJECTION_FILE=/tmp/zenlog-time

mkdir -p "$ZENLOG_DIR"
find "$ZENLOG_DIR" -mindepth 1 -delete

echo 1508544000 > $ZENLOG_TIME_INJECTION_FILE

export PATH="$medir/..:$PATH"
script -qec zenlog /dev/null
