#!/usr/bin/env ruby

require 'pathname'
require 'optionparser'
require_relative 'zenlog'

fail_unless_in_zenlog

raw = false
nth = -1
pid = ENV[ZENLOG_PID].to_i

OptionParser.new { |opts|
  opts.on("-r", "Show RAW filenames, instead of SAN filenames.") do
    raw = true
  end

  opts.on("-pPID", "PID of a zenlog session to show log instead of current session.") do |v|
    pid = v.to_i
  end
}.order!

BuiltIns.history(raw, pid, 0)
