#!/usr/bin/perl -w

use strict;
use Getopt::Std;

my %opts = ();

getopts("p:r", \%opts) or exit 1;

my $pid = $opts{p} // $ENV{ZENLOG_PID};

my $file = readlink("$ENV{ZENLOG_DIR}/pids/$pid/P") or exit 1;

$file =~ s/\bSAN\b/RAW/ if $opts{r};

print $file, "\n";


# It was too slow.
# #!/usr/bin/env ruby
#
# require 'pathname'
# require 'optionparser'
# require_relative 'zenlog'
#
# BuiltIns.fail_unless_in_zenlog
#
# raw = false
# nth = -1
# pid = ENV[ZENLOG_PID].to_i
#
# OptionParser.new { |opts|
#   opts.on("-r", "Show RAW filenames, instead of SAN filenames.") do
#     raw = true
#   end
#
#   opts.on("-pPID", "PID of a zenlog session to show log instead of current session.") do |v|
#     pid = v.to_i
#   end
# }.order!
#
# BuiltIns.history(raw, pid, 0)
#
