#!/bin/bash

# Basic Zenlog bash helper functions.

# Install it with:
# . <(zenlog sh-helper)

cat <<'EOF'
# Return sucess when in zenlog.
function in_zenlog() {
  zenlog in-zenlog
}

# Run a command without logging the output.
function _zenlog_nolog() {
  "${@}"
}
alias 184=_zenlog_nolog

# Run a command with forcing log, regardless of ZENLOG_ALWAYS_184_COMMANDS.
function _zenlog_force_log() {
  "${@}"
}
alias 186=_zenlog_force_log

# Print the current command's command line.  Use with "zenlog start-command".
function bash_last_command() {
  # Use echo to remove newlines.
  echo $(HISTTIMEFORMAT= history 1 | sed -e 's/^ *[0-9][0-9]* *//')
}

function bash_dump_env() {
  {
    echo "PWD: $(pwd)"
    echo "git HEAD: $(git describe --contains --all HEAD)"
    # env
    declare -p
  } 2>/dev/null
}

EOF
