#!/bin/bash

set -e
. <(zenlog -s)

zenlog_fail_if_not_in_zenlog || exit 1

num=10
TEXT_ONLY=0

eval "$(getopt.pl -d 'Show filename-like strings from recent zenlog logs.' '
n:  num=%        # Use recent NUM log files. (N <= 10).
t   TEXT_ONLY=1  # Show text files only.
' "$@")"

export TEXT_ONLY

# Use zenlog-contents instead of cat to exclude prompts
zenlog-last-n-contents -R -n $num  | $0.pl | global-unique | fzf +s -m --ansi | tr '\n' ' '
