#!/usr/bin/perl -w

use strict;
use FindBin;
use lib "$FindBin::Bin";
use POSIX;
use Getopt::Long;
use ZenlogCommon;

use constant DEBUG => 0;

sub zenlog_start() {
  my ($reader_fd, $writer_fd) = POSIX::pipe();
  $reader_fd or die "$0: pipe() failed: $!\n";

  printf STDERR ("# pipe opened, read=%d, write=%d\n",
      $reader_fd, $writer_fd) if DEBUG;

  if (my $pid = fork()) {
    POSIX::close($reader_fd);
    # Parent
    exec("script",
      "-fqc",
      "export ZENLOG_TTY=\$(tty); exec /bin/bash -l",
      "/proc/self/fd/$writer_fd") or die "$0: failed to start script: $!\n";
  }
  # Child
  POSIX::close($writer_fd);
  open(my $reader, "<&=", $reader_fd) or die "$0: fdopen failed: $!\n";
}

#---------------------------------------------------------------------
# Start
#---------------------------------------------------------------------

my $zenlog_start_command = "$ENV{SHELL} -l";

# If the rc file exists, load it.
my $RC_FILE = "$ENV{HOME}/.zenlogprc";
require $RC_FILE if -f $RC_FILE;














